name: Build /public and delpoy to gh-pages with docker container

on:
  push:
    branches:
      - docker
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: mkdir public
      
      - run: mkdir data

      - run: git clone https://github.com/sroertgen/oer-metadata-hub-vocab.git data/

      - name: build public dir with docker image 
        run: docker run -v $(pwd)/public:/app/public -v $(pwd)/data:/app/data laocoon667/skohub-vocab:latest

      - uses: actions/upload-artifact@master
        with:
          name: public
          path: public

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
